// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace with your Firebase project configuration

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPIKsb3RETRyHJzIYL8IytNk0UVWMB_Po',
    appId: '1:1009952351430:android:31d0b014b96b538483a3c7',
    messagingSenderId: '1009952351430',
    projectId: 'ditonton-3cf3f',
    storageBucket: 'ditonton-3cf3f.firebasestorage.app',
  );

  // Run: flutterfire configure

  // TODO: Replace with your Firebase project configuration

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDG65IW9uVohT0fRFj88GP_6Ol1YLqAsk',
    appId: '1:1009952351430:ios:520be06a2620042583a3c7',
    messagingSenderId: '1009952351430',
    projectId: 'ditonton-3cf3f',
    storageBucket: 'ditonton-3cf3f.firebasestorage.app',
    iosBundleId: 'com.dicoding.ditonton',
  );

  // Run: flutterfire configure
}
